// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	GooseDBVersion      string
	PaymentTransactions string
	Subscriptions       string
	Users               string
}{
	GooseDBVersion:      "goose_db_version",
	PaymentTransactions: "payment_transactions",
	Subscriptions:       "subscriptions",
	Users:               "users",
}
