// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// PaymentTransaction is an object representing the database table.
type PaymentTransaction struct {
	ID                    string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID                string    `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Amount                int       `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Currency              string    `boil:"currency" json:"currency" toml:"currency" yaml:"currency"`
	Status                string    `boil:"status" json:"status" toml:"status" yaml:"status"`
	CreatedAt             time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	StripePaymentIntentID string    `boil:"stripe_payment_intent_id" json:"stripe_payment_intent_id" toml:"stripe_payment_intent_id" yaml:"stripe_payment_intent_id"`

	R *paymentTransactionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L paymentTransactionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PaymentTransactionColumns = struct {
	ID                    string
	UserID                string
	Amount                string
	Currency              string
	Status                string
	CreatedAt             string
	StripePaymentIntentID string
}{
	ID:                    "id",
	UserID:                "user_id",
	Amount:                "amount",
	Currency:              "currency",
	Status:                "status",
	CreatedAt:             "created_at",
	StripePaymentIntentID: "stripe_payment_intent_id",
}

var PaymentTransactionTableColumns = struct {
	ID                    string
	UserID                string
	Amount                string
	Currency              string
	Status                string
	CreatedAt             string
	StripePaymentIntentID string
}{
	ID:                    "payment_transactions.id",
	UserID:                "payment_transactions.user_id",
	Amount:                "payment_transactions.amount",
	Currency:              "payment_transactions.currency",
	Status:                "payment_transactions.status",
	CreatedAt:             "payment_transactions.created_at",
	StripePaymentIntentID: "payment_transactions.stripe_payment_intent_id",
}

// Generated where

type whereHelperstring struct{ field string }

func (w whereHelperstring) EQ(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperstring) NEQ(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperstring) LT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperstring) LTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperstring) GT(x string) qm.QueryMod     { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperstring) GTE(x string) qm.QueryMod    { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperstring) LIKE(x string) qm.QueryMod   { return qm.Where(w.field+" LIKE ?", x) }
func (w whereHelperstring) NLIKE(x string) qm.QueryMod  { return qm.Where(w.field+" NOT LIKE ?", x) }
func (w whereHelperstring) ILIKE(x string) qm.QueryMod  { return qm.Where(w.field+" ILIKE ?", x) }
func (w whereHelperstring) NILIKE(x string) qm.QueryMod { return qm.Where(w.field+" NOT ILIKE ?", x) }
func (w whereHelperstring) IN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperstring) NIN(slice []string) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var PaymentTransactionWhere = struct {
	ID                    whereHelperstring
	UserID                whereHelperstring
	Amount                whereHelperint
	Currency              whereHelperstring
	Status                whereHelperstring
	CreatedAt             whereHelpertime_Time
	StripePaymentIntentID whereHelperstring
}{
	ID:                    whereHelperstring{field: "\"payment_transactions\".\"id\""},
	UserID:                whereHelperstring{field: "\"payment_transactions\".\"user_id\""},
	Amount:                whereHelperint{field: "\"payment_transactions\".\"amount\""},
	Currency:              whereHelperstring{field: "\"payment_transactions\".\"currency\""},
	Status:                whereHelperstring{field: "\"payment_transactions\".\"status\""},
	CreatedAt:             whereHelpertime_Time{field: "\"payment_transactions\".\"created_at\""},
	StripePaymentIntentID: whereHelperstring{field: "\"payment_transactions\".\"stripe_payment_intent_id\""},
}

// PaymentTransactionRels is where relationship names are stored.
var PaymentTransactionRels = struct {
	User string
}{
	User: "User",
}

// paymentTransactionR is where relationships are stored.
type paymentTransactionR struct {
	User *User `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*paymentTransactionR) NewStruct() *paymentTransactionR {
	return &paymentTransactionR{}
}

func (r *paymentTransactionR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

// paymentTransactionL is where Load methods for each relationship are stored.
type paymentTransactionL struct{}

var (
	paymentTransactionAllColumns            = []string{"id", "user_id", "amount", "currency", "status", "created_at", "stripe_payment_intent_id"}
	paymentTransactionColumnsWithoutDefault = []string{"user_id", "amount", "currency", "status", "stripe_payment_intent_id"}
	paymentTransactionColumnsWithDefault    = []string{"id", "created_at"}
	paymentTransactionPrimaryKeyColumns     = []string{"id"}
	paymentTransactionGeneratedColumns      = []string{}
)

type (
	// PaymentTransactionSlice is an alias for a slice of pointers to PaymentTransaction.
	// This should almost always be used instead of []PaymentTransaction.
	PaymentTransactionSlice []*PaymentTransaction
	// PaymentTransactionHook is the signature for custom PaymentTransaction hook methods
	PaymentTransactionHook func(context.Context, boil.ContextExecutor, *PaymentTransaction) error

	paymentTransactionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	paymentTransactionType                 = reflect.TypeOf(&PaymentTransaction{})
	paymentTransactionMapping              = queries.MakeStructMapping(paymentTransactionType)
	paymentTransactionPrimaryKeyMapping, _ = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, paymentTransactionPrimaryKeyColumns)
	paymentTransactionInsertCacheMut       sync.RWMutex
	paymentTransactionInsertCache          = make(map[string]insertCache)
	paymentTransactionUpdateCacheMut       sync.RWMutex
	paymentTransactionUpdateCache          = make(map[string]updateCache)
	paymentTransactionUpsertCacheMut       sync.RWMutex
	paymentTransactionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var paymentTransactionAfterSelectMu sync.Mutex
var paymentTransactionAfterSelectHooks []PaymentTransactionHook

var paymentTransactionBeforeInsertMu sync.Mutex
var paymentTransactionBeforeInsertHooks []PaymentTransactionHook
var paymentTransactionAfterInsertMu sync.Mutex
var paymentTransactionAfterInsertHooks []PaymentTransactionHook

var paymentTransactionBeforeUpdateMu sync.Mutex
var paymentTransactionBeforeUpdateHooks []PaymentTransactionHook
var paymentTransactionAfterUpdateMu sync.Mutex
var paymentTransactionAfterUpdateHooks []PaymentTransactionHook

var paymentTransactionBeforeDeleteMu sync.Mutex
var paymentTransactionBeforeDeleteHooks []PaymentTransactionHook
var paymentTransactionAfterDeleteMu sync.Mutex
var paymentTransactionAfterDeleteHooks []PaymentTransactionHook

var paymentTransactionBeforeUpsertMu sync.Mutex
var paymentTransactionBeforeUpsertHooks []PaymentTransactionHook
var paymentTransactionAfterUpsertMu sync.Mutex
var paymentTransactionAfterUpsertHooks []PaymentTransactionHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *PaymentTransaction) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *PaymentTransaction) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *PaymentTransaction) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *PaymentTransaction) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *PaymentTransaction) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *PaymentTransaction) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *PaymentTransaction) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *PaymentTransaction) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *PaymentTransaction) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range paymentTransactionAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddPaymentTransactionHook registers your hook function for all future operations.
func AddPaymentTransactionHook(hookPoint boil.HookPoint, paymentTransactionHook PaymentTransactionHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		paymentTransactionAfterSelectMu.Lock()
		paymentTransactionAfterSelectHooks = append(paymentTransactionAfterSelectHooks, paymentTransactionHook)
		paymentTransactionAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		paymentTransactionBeforeInsertMu.Lock()
		paymentTransactionBeforeInsertHooks = append(paymentTransactionBeforeInsertHooks, paymentTransactionHook)
		paymentTransactionBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		paymentTransactionAfterInsertMu.Lock()
		paymentTransactionAfterInsertHooks = append(paymentTransactionAfterInsertHooks, paymentTransactionHook)
		paymentTransactionAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		paymentTransactionBeforeUpdateMu.Lock()
		paymentTransactionBeforeUpdateHooks = append(paymentTransactionBeforeUpdateHooks, paymentTransactionHook)
		paymentTransactionBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		paymentTransactionAfterUpdateMu.Lock()
		paymentTransactionAfterUpdateHooks = append(paymentTransactionAfterUpdateHooks, paymentTransactionHook)
		paymentTransactionAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		paymentTransactionBeforeDeleteMu.Lock()
		paymentTransactionBeforeDeleteHooks = append(paymentTransactionBeforeDeleteHooks, paymentTransactionHook)
		paymentTransactionBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		paymentTransactionAfterDeleteMu.Lock()
		paymentTransactionAfterDeleteHooks = append(paymentTransactionAfterDeleteHooks, paymentTransactionHook)
		paymentTransactionAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		paymentTransactionBeforeUpsertMu.Lock()
		paymentTransactionBeforeUpsertHooks = append(paymentTransactionBeforeUpsertHooks, paymentTransactionHook)
		paymentTransactionBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		paymentTransactionAfterUpsertMu.Lock()
		paymentTransactionAfterUpsertHooks = append(paymentTransactionAfterUpsertHooks, paymentTransactionHook)
		paymentTransactionAfterUpsertMu.Unlock()
	}
}

// One returns a single paymentTransaction record from the query.
func (q paymentTransactionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PaymentTransaction, error) {
	o := &PaymentTransaction{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: failed to execute a one query for payment_transactions")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all PaymentTransaction records from the query.
func (q paymentTransactionQuery) All(ctx context.Context, exec boil.ContextExecutor) (PaymentTransactionSlice, error) {
	var o []*PaymentTransaction

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "entity: failed to assign all query results to PaymentTransaction slice")
	}

	if len(paymentTransactionAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all PaymentTransaction records in the query.
func (q paymentTransactionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to count payment_transactions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q paymentTransactionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "entity: failed to check if payment_transactions exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *PaymentTransaction) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (paymentTransactionL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybePaymentTransaction interface{}, mods queries.Applicator) error {
	var slice []*PaymentTransaction
	var object *PaymentTransaction

	if singular {
		var ok bool
		object, ok = maybePaymentTransaction.(*PaymentTransaction)
		if !ok {
			object = new(PaymentTransaction)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePaymentTransaction)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePaymentTransaction))
			}
		}
	} else {
		s, ok := maybePaymentTransaction.(*[]*PaymentTransaction)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePaymentTransaction)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePaymentTransaction))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &paymentTransactionR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &paymentTransactionR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.PaymentTransactions = append(foreign.R.PaymentTransactions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.PaymentTransactions = append(foreign.R.PaymentTransactions, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the paymentTransaction to the related item.
// Sets o.R.User to related.
// Adds o to related.R.PaymentTransactions.
func (o *PaymentTransaction) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"payment_transactions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, paymentTransactionPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &paymentTransactionR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			PaymentTransactions: PaymentTransactionSlice{o},
		}
	} else {
		related.R.PaymentTransactions = append(related.R.PaymentTransactions, o)
	}

	return nil
}

// PaymentTransactions retrieves all the records using an executor.
func PaymentTransactions(mods ...qm.QueryMod) paymentTransactionQuery {
	mods = append(mods, qm.From("\"payment_transactions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"payment_transactions\".*"})
	}

	return paymentTransactionQuery{q}
}

// FindPaymentTransaction retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPaymentTransaction(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*PaymentTransaction, error) {
	paymentTransactionObj := &PaymentTransaction{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"payment_transactions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, paymentTransactionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "entity: unable to select from payment_transactions")
	}

	if err = paymentTransactionObj.doAfterSelectHooks(ctx, exec); err != nil {
		return paymentTransactionObj, err
	}

	return paymentTransactionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PaymentTransaction) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("entity: no payment_transactions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paymentTransactionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	paymentTransactionInsertCacheMut.RLock()
	cache, cached := paymentTransactionInsertCache[key]
	paymentTransactionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			paymentTransactionAllColumns,
			paymentTransactionColumnsWithDefault,
			paymentTransactionColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"payment_transactions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"payment_transactions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "entity: unable to insert into payment_transactions")
	}

	if !cached {
		paymentTransactionInsertCacheMut.Lock()
		paymentTransactionInsertCache[key] = cache
		paymentTransactionInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the PaymentTransaction.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PaymentTransaction) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	paymentTransactionUpdateCacheMut.RLock()
	cache, cached := paymentTransactionUpdateCache[key]
	paymentTransactionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			paymentTransactionAllColumns,
			paymentTransactionPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("entity: unable to update payment_transactions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"payment_transactions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, paymentTransactionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, append(wl, paymentTransactionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update payment_transactions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by update for payment_transactions")
	}

	if !cached {
		paymentTransactionUpdateCacheMut.Lock()
		paymentTransactionUpdateCache[key] = cache
		paymentTransactionUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q paymentTransactionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all for payment_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected for payment_transactions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PaymentTransactionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("entity: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paymentTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"payment_transactions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, paymentTransactionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to update all in paymentTransaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to retrieve rows affected all in update all paymentTransaction")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PaymentTransaction) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("entity: no payment_transactions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(paymentTransactionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	paymentTransactionUpsertCacheMut.RLock()
	cache, cached := paymentTransactionUpsertCache[key]
	paymentTransactionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			paymentTransactionAllColumns,
			paymentTransactionColumnsWithDefault,
			paymentTransactionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			paymentTransactionAllColumns,
			paymentTransactionPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("entity: unable to upsert payment_transactions, could not build update column list")
		}

		ret := strmangle.SetComplement(paymentTransactionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(paymentTransactionPrimaryKeyColumns) == 0 {
				return errors.New("entity: unable to upsert payment_transactions, could not build conflict column list")
			}

			conflict = make([]string, len(paymentTransactionPrimaryKeyColumns))
			copy(conflict, paymentTransactionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"payment_transactions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(paymentTransactionType, paymentTransactionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "entity: unable to upsert payment_transactions")
	}

	if !cached {
		paymentTransactionUpsertCacheMut.Lock()
		paymentTransactionUpsertCache[key] = cache
		paymentTransactionUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single PaymentTransaction record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PaymentTransaction) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("entity: no PaymentTransaction provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), paymentTransactionPrimaryKeyMapping)
	sql := "DELETE FROM \"payment_transactions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete from payment_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by delete for payment_transactions")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q paymentTransactionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("entity: no paymentTransactionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from payment_transactions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for payment_transactions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PaymentTransactionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(paymentTransactionBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paymentTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"payment_transactions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paymentTransactionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "entity: unable to delete all from paymentTransaction slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "entity: failed to get rows affected by deleteall for payment_transactions")
	}

	if len(paymentTransactionAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PaymentTransaction) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPaymentTransaction(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PaymentTransactionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PaymentTransactionSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), paymentTransactionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"payment_transactions\".* FROM \"payment_transactions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, paymentTransactionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "entity: unable to reload all in PaymentTransactionSlice")
	}

	*o = slice

	return nil
}

// PaymentTransactionExists checks if the PaymentTransaction row exists.
func PaymentTransactionExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"payment_transactions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "entity: unable to check if payment_transactions exists")
	}

	return exists, nil
}

// Exists checks if the PaymentTransaction row exists.
func (o *PaymentTransaction) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PaymentTransactionExists(ctx, exec, o.ID)
}
