// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mock/service.go
//

// Package mock_word is a generated GoMock package.
package mock_word

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	domain "github.com/Lionel-Wilson/My-Language-Aibou-API/internal/word/domain"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetWordDefinition mocks base method.
func (m *MockService) GetWordDefinition(ctx context.Context, word, nativeLanguage string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWordDefinition", ctx, word, nativeLanguage)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWordDefinition indicates an expected call of GetWordDefinition.
func (mr *MockServiceMockRecorder) GetWordDefinition(ctx, word, nativeLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWordDefinition", reflect.TypeOf((*MockService)(nil).GetWordDefinition), ctx, word, nativeLanguage)
}

// GetWordHistory mocks base method.
func (m *MockService) GetWordHistory(ctx context.Context, word, nativeLanguage string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWordHistory", ctx, word, nativeLanguage)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWordHistory indicates an expected call of GetWordHistory.
func (mr *MockServiceMockRecorder) GetWordHistory(ctx, word, nativeLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWordHistory", reflect.TypeOf((*MockService)(nil).GetWordHistory), ctx, word, nativeLanguage)
}

// GetWordSynonyms mocks base method.
func (m *MockService) GetWordSynonyms(ctx context.Context, word, nativeLanguage string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWordSynonyms", ctx, word, nativeLanguage)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWordSynonyms indicates an expected call of GetWordSynonyms.
func (mr *MockServiceMockRecorder) GetWordSynonyms(ctx, word, nativeLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWordSynonyms", reflect.TypeOf((*MockService)(nil).GetWordSynonyms), ctx, word, nativeLanguage)
}

// Lookup mocks base method.
func (m *MockService) Lookup(ctx context.Context, word, nativeLanguage string) (*domain.LookupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", ctx, word, nativeLanguage)
	ret0, _ := ret[0].(*domain.LookupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockServiceMockRecorder) Lookup(ctx, word, nativeLanguage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockService)(nil).Lookup), ctx, word, nativeLanguage)
}

// ValidateWord mocks base method.
func (m *MockService) ValidateWord(word string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateWord", word)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateWord indicates an expected call of ValidateWord.
func (mr *MockServiceMockRecorder) ValidateWord(word any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateWord", reflect.TypeOf((*MockService)(nil).ValidateWord), word)
}
